name: Build and Publish 
run-name: ${{ github.actor }} is building and publishing
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Using Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: NPM Install
        run: npm install
      - name: Build App
        run: npm run build
        env:
          VUE_APP_FIREBASE_API_KEY: ${{ secret.VUE_APP_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secret.VUE_APP_FIREBASE_AUTH_DOMAIN }}
          VUE_APP_FIREBASE_PROJECT_ID: ${{ secret.VUE_APP_FIREBASE_PROJECT_ID }}
          VUE_APP_FIREBASE_STORAGE_BUCKET: ${{ secret.VUE_APP_FIREBASE_STORAGE_BUCKET }}
          VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secret.VUE_APP_FIREBASE_MESSAGING_SENDER_ID }}
          VUE_APP_FIREBASE_APP_ID: ${{ secret.VUE_APP_FIREBASE_APP_ID }}
          VUE_APP_FIREBASE_MEASUREMENT_ID: ${{ secret.VUE_APP_FIREBASE_MEASUREMENT_ID }}
      - name: Upload dist to S3
        run: aws s3 cp ./dist s3://${{ vars.S3BUCKETNAME }} --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
